### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by CorruptionHades** [turn/RedefineClassAgent#1]
When loading the agent into the target program it creates a new thread and also for some reason doesnt have access to the classes because I get this error
Exception in thread "Attach Listener" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:491)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallAgentmain(InstrumentationImpl.java:513)
Caused by: javassist.NotFoundException: program.Utilities
	at javassist.ClassPool.get(ClassPool.java:430)
	at agent.Agent.agentmain(Agent.java:46)
	... 6 more
Agent failed to start!

line 46: CtClass ctClass = classPool.get("program.Utilities");

**Comment by CopperEagle** [comment]
@CorruptionHades I know this is late but for anyone else that has this problem: Try `-Djdk.attach.allowAttachSelf=true` when running the JVM.
